#! /bin/bash

WHAT=$1

set -x

GIT_OWNER=plumed-nest
GIT_REPO=plumed-nest

if [[ "${GITHUB_REF##*/}" = master ]] ; then
  PUSH_REPO=plumed-nest/plumed-nest.github.io.git
elif [[ "${GITHUB_REF##*/}" = test ]] ; then
  PUSH_REPO=plumed-nest/test-site.git
else
  echo "branch ${GITHUB_REF##*/}, skipping push"
  exit 0
fi

hash=$( git log -1 --format="%h")

root="$PWD"
mkdir -p tmp/$$

tar cf all.tar $@

cd tmp/$$
tar xf ../../all.tar

export GIT_BOT_EMAIL=giovanni.bussi+plumedbot@gmail.com

git init
git config user.email giovanni.bussi+plumedbot@gmail.com
git config user.name plumedbot
set +x
git remote add origin https://plumedbot:$PLUMED_NEST_GITHUB_TOKEN@github.com/$PUSH_REPO
set -x

# create README.md
cat > README.md << EOF
Welcome to PLUMED-NEST!
-----------------------------

EOF

# add general informations
cat Info.md >> README.md

cp $root/nest.png .
cp $root/pigeon.png .
cp $root/CNAME .

if [[ "${GITHUB_REF##*/}" = test ]] ; then
  sed "s/PLUMED-NEST/PLUMED-NEST-TEST-SITE/" _config.yml > _config.yml.tmp
  mv _config.yml.tmp _config.yml
  cat "baseurl: /test-site" >> _config.yml
  rm CNAME
fi

git add --all .
# >/dev/null to avoid excessive noise on travis log
git commit -m "Update to @$hash" >/dev/null
# -q and 2> is not to show the PLUMED_NEST_GITHUB_TOKEN log
git push -q -f origin master 2> /dev/null 
