#! /bin/bash

WHAT=$1

set -x

GIT_OWNER=$(  echo $TRAVIS_REPO_SLUG | sed "s/\/.*$//" )
GIT_REPO=$(   echo $TRAVIS_REPO_SLUG | sed "s/^.*\///" )

if [ "$TRAVIS_PULL_REQUEST" != false ] ; then
  echo "Building from a pull request, nothing to push"
  exit 0
fi

hash=$( git log -1 --format="%h")

root="$PWD"
mkdir -p tmp/$$

tar cf all.tar $@

cd tmp/$$
tar xf ../../all.tar

export GIT_BOT_EMAIL=giovanni.bussi+plumedbot@gmail.com

git init
git config user.email giovanni.bussi+plumedbot@gmail.com
git config user.name plumedbot
set +x
git remote add origin https://plumedbot:$GIT_TOKEN@github.com/plumed/plumed-nest-site.git
set -x

cat > README.md << EOF
PLUMED-NEST: ${TRAVIS_BRANCH}
-----------------------------
$hash

EOF

cat ../list.tmp >> README.md

git add --all .
# >/dev/null to avoid excessive noise on travis log
git commit -m "Update to @$hash" >/dev/null
# -q and 2> is not to show the GIT_TOKEN on Travis log
git push -q -f origin master 2> /dev/null 
